services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecoride
      POSTGRES_USER: ecoride
      POSTGRES_PASSWORD: ecoride
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"   # UI: http://localhost:8025

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
      - mailhog
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://ecoride:ecoride@db:5432/ecoride
      MONGODB_URI: mongodb://mongo:27017/ecoride
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_FROM: "EcoRide <no-reply@ecoride.local>"
      JWT_SECRET: "change-me-in-prod"

volumes:
  db-data:
  mongo-data:
